{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
    - {{ . }}
  {{- end }}
  gateways:
  - istio-ingress/gateway-platform
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}