{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "nginx-demo.fullname" . }}-psp
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nginx-demo.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "nginx-demo.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
