{{- if .Values.podSecurityPolicy.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nginx-demo.fullname" . }}-psp
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "nginx-demo.fullname" . }}
{{- end }}
